---
- name: SERVER BOOTSTRAP
  hosts: ociserver
  become: yes
  roles:
    - ubuntu-bootstrap

- name: DOCKER INSTALLATION
  hosts: ociserver
  become: yes
  roles:
    - docker

- name: NOIP CLIENT
  hosts: ociserver
  become: yes
  roles:
    - noip
