roles:
  - name: robertdebock.bootstrap
    version: 6.2.2
  - name: robertdebock.update
    version: 3.1.7
  - name: geerlingguy.ntp
    version: 2.3.3
  - name: geerlingguy.swap
    version: 1.0.2
  - name: geerlingguy.pip
    version: 3.0.1
  - name: robertdebock.reboot
    version: 3.2.4
  - name: geerlingguy.docker
    version: 7.0.2
